name: ci-workflow

on: [push, pull_request]

jobs:
  s390x-build:
    runs-on: ubuntu-18.04
    name: Build on s390x
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: /home/runner/work/nifi/nifi
      - uses: uraimo/run-on-arch-action@v2.0.8
        with:
          architecture: s390x
          distribution: ubuntu18.04
          env: |
            MAVEN_OPTS: -Xmx2g -XX:ReservedCodeCacheSize=1g -XX:+UseG1GC -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dmaven.surefire.arguments="-Duser.language=en -Duser.region=AU -Duser.timezone=Australia/Melbourne"
            JAVA_HOME: /usr/lib/jvm/java-11-openjdk-s390x/
          run: |
            set -euo pipefail
            apt-get -q -y update
            apt-get install -q -y --no-install-recommends \
            wget \
            tar \
            curl \
            patch \
            libatomic1 \
            git \
            sudo \
            ca-certificates-java
            wget https://raw.githubusercontent.com/vibhutisawant/crate/master/patch.diff
            git apply patch.diff
            mvn -V -T 0.7C package verify -B -Pcontrib-check,include-grpc -Ddir-only -ntp -ff -pl -nifi-assembly,-nifi-toolkit/nifi-toolkit-assembly,-nifi-system-tests -nsu
          
